apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-platform-v2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hamzaBKR/CI-CD-Vote-app.git
    targetRevision: main
    path: infrastructure/helm/feedback-platform
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: namespace
          value: feedback-v2
        - name: ingress.enabled
          value: "false"

  destination:
    server: https://kubernetes.default.svc
    namespace: feedback-v2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
