{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feedback-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.voteHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.voteApp.name }}
                port:
                  number: {{ .Values.voteApp.service.port }}
    - host: {{ .Values.ingress.resultHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.resultApp.name }}
                port:
                  number: {{ .Values.resultApp.service.port }}
{{- end }}
